spring.application.name=ComputerAssociation


logging.file.path=logs

logging.level.root=INFO
logging.level.com.example.computerassociation=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.org.apache.ibatis=INFO


spring.datasource.url=jdbc:postgresql://localhost:5432/computer_association
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml
mybatis-plus.type-aliases-package=com.example.computerassociation.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl